### ISSUE TITLE
Start moving to a sources list file by loading the sources and their URLs from a YAML file in libguinget's resources instead of it being hardcoded.

### ISSUE THREAD

**Issue by DrewNaylor** [DrewNaylor/guinget#49]
This sources file can be something like

```yaml
source
  # Source ID used to differentiate between 
  # sources. Will be used in place of the "-display-name:"
  # field if that one's not available.
  id: "winget"
    # What's shown in the "refresh cache" 
    # window. Maybe it would be a good idea to also 
    # display whether we're updating the database or 
    # the manifests at the current time. This could 
    # also be used in a sources manager program.
    -display-name: "Microsoft/winget-pkgs"
    # URLs that the manifest archive and database
    # are downloaded from.
    -manifest-archive-url: "https://github.com/Microsoft/winget-pkgs"
    -database-url: "(insert database URL here)"
    # Can't use the display name to determine the 
    # cache root directories, so we'll specify them. 
    # Getting this from the URL automatically 
    # would be a good idea.
    -manifest-archive-cache-dir-root: "winget-pkgs"
    -database-cache-dir-root: "winget-db"
    # While unlikely, it's possible that other 
    # databases could have a different filename 
    # for itself, so this is just in case.
    -database-file-name: "Index.db"
    # Some repos have all the manifests in the 
    # root rather than a subfolder, such as the 
    # mirror repo on GitHub. By default, we'll look 
    # under the "manifests" subfolder, though.
    -manifests-in-root: "False"
    -manifest-path-subfolder: "\manifests\"

source
    id: "msstore"
    # Etc.
```

Additionally, this will have to have a field to determine whether manifests are discovered based on package ID and version from the database (default for winget-pkgs/winget-db), or whether it has to grab the manifests from the Internet based on a path from the `pathparts` table (which would have to be used for the Store source). The Store database has pathparts all in one string, so that should be easy as long as it stays that way.
